'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const clone=v=>JSON.parse(JSON.stringify(v));
const canon=v=>Array.isArray(v)?v.map(canon):(v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v);
const canonicalFingerprint=v=>{const x=clone(v);x.fingerprint_sha256='';return `sha256:${crypto.createHash('sha256').update(JSON.stringify(canon(x)),'utf8').digest('hex')}`;};

class FCLHandoffError extends Error{constructor(m){super(m);this.name='FCLHandoffError';}}
const req=(c,m)=>{if(!c)throw new FCLHandoffError(m);};
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v,k,l)=>{req(obj(v),`${l} must be an object`);req(JSON.stringify(Object.keys(v).sort())===JSON.stringify([...k].sort()),`${l} keys mismatch`);};
const str=(v,l,p)=>{req(typeof v==='string'&&v.length>0,`${l} must be a non-empty string`);if(p)req(p.test(v),`${l} has invalid format`);};
const nni=(v,l)=>req(Number.isInteger(v)&&v>=0,`${l} must be a non-negative integer`);
const arr=(v,l,min=0)=>{req(Array.isArray(v)&&v.length>=min,`${l} invalid`);v.forEach((x,i)=>str(x,`${l}[${i}]`));req(new Set(v).size===v.length,`${l} must contain unique values`);};
const time=(v,l)=>{str(v,l);const x=Date.parse(v);req(Number.isFinite(x),`${l} invalid date-time`);return x;};
const ID=/^[a-z][a-z0-9-]{2,95}$/,FP=/^sha256:[0-9a-f]{64}$/,SHA=/^[0-9a-f]{40}$/;
const P=['protocol','version','receipt_type','chain_id','run_id','run_epoch','intent_ref','chain_length','head_sequence','head_fingerprint','human_status','last_confirmed_progress_at','last_progress_age_seconds','current_phase','waiting_on','next_observable_event','next_safe_action','checkpoint_ref','terminal','continuation_available','execution_admitted','authority_established','transport_delivery_proves_progress','private_reasoning_included','projected_at','fingerprint_sha256'];
function validateProjection(p,l){exact(p,P,l);req(p.protocol==='FCL'&&p.version==='0.1'&&p.receipt_type==='ProgressProjectionReceipt',`${l} header mismatch`);str(p.chain_id,`${l}.chain_id`,ID);str(p.run_id,`${l}.run_id`,ID);nni(p.run_epoch,`${l}.run_epoch`);str(p.intent_ref,`${l}.intent_ref`);req(Number.isInteger(p.chain_length)&&p.chain_length>0&&p.chain_length===p.head_sequence+1,`${l}.chain_length/head_sequence invalid`);nni(p.head_sequence,`${l}.head_sequence`);str(p.head_fingerprint,`${l}.head_fingerprint`,FP);req(['ACTIVE','WAITING','STALL_SUSPECTED','CLOSED','CONTINUATION_AVAILABLE'].includes(p.human_status),`${l}.human_status invalid`);time(p.last_confirmed_progress_at,`${l}.last_confirmed_progress_at`);nni(p.last_progress_age_seconds,`${l}.last_progress_age_seconds`);str(p.current_phase,`${l}.current_phase`);if(p.waiting_on!==null)str(p.waiting_on,`${l}.waiting_on`);str(p.next_observable_event,`${l}.next_observable_event`);req(['WAIT_FOR_NEXT_RECEIPT','WAIT_OR_INTERRUPT','CREATE_SUCCESSOR_RUN'].includes(p.next_safe_action),`${l}.next_safe_action invalid`);if(p.checkpoint_ref!==null)str(p.checkpoint_ref,`${l}.checkpoint_ref`);req(typeof p.terminal==='boolean'&&typeof p.continuation_available==='boolean',`${l}.terminal flags invalid`);['execution_admitted','authority_established','transport_delivery_proves_progress','private_reasoning_included'].forEach(k=>req(p[k]===false,`${l}.${k} must remain false`));time(p.projected_at,`${l}.projected_at`);str(p.fingerprint_sha256,`${l}.fingerprint_sha256`,FP);req(p.fingerprint_sha256===canonicalFingerprint(p),`${l}.fingerprint_sha256 mismatch`);if(p.terminal){req(p.continuation_available&&p.human_status==='CONTINUATION_AVAILABLE'&&p.next_safe_action==='CREATE_SUCCESSOR_RUN',`${l}: terminal projection semantics invalid`);}else{req(!p.continuation_available&&!['CLOSED','CONTINUATION_AVAILABLE'].includes(p.human_status)&&p.next_safe_action!=='CREATE_SUCCESSOR_RUN',`${l}: non-terminal projection semantics invalid`);}return true;}
const D=['protocol','version','receipt_type','session_id','event_count','display_update_count','accepted_chain_id','accepted_run_id','accepted_run_epoch','accepted_intent_ref','accepted_head_sequence','accepted_projection_fingerprint','accepted_display_predecessor_projection_fingerprint','human_status','last_confirmed_progress_at','current_phase','waiting_on','next_observable_event','next_safe_action','terminal','continuation_available','dispositions','delivery_creates_progress','duplicate_delivery_counts_as_progress','reconnect_restores_authority','stale_projection_can_replace_display','transport_events_prove_liveness','execution_admitted','authority_established','private_reasoning_included','assessed_at','fingerprint_sha256'];
const X=['delivery_sequence','event_kind','disposition','projection_fingerprint','accepted_head_sequence_after','accepted_projection_fingerprint_after','display_state_advanced','new_progress_created_by_delivery','authority_established','execution_admitted'];
const C=['protocol','version','receipt_type','predecessor_run_id','predecessor_run_epoch','predecessor_terminal_state','terminal_receipt_fingerprint','predecessor_resurrection_admitted','predecessor_authority_reacquired','successor_run_id','successor_run_epoch','successor_requires_fresh_authority','transferable_hidden_reasoning','intent_ref','last_checkpoint_ref','completed_refs','unresolved_work','constraints','non_effects','status','created_at','fingerprint_sha256'];
const H=['protocol','version','profile','handoff_id','origin','predecessor_delivery_assessment','predecessor_terminal_projection','continuation_receipt','successor_projection','successor_display_predecessor_projection_fingerprint','handoff_at'];

function validateDelivery(r){
 exact(r,D,'predecessor_delivery_assessment');req(r.protocol==='FCL'&&r.version==='0.1'&&r.receipt_type==='ProjectionDeliveryAssessmentReceipt','delivery assessment header mismatch');
 str(r.session_id,'delivery.session_id',ID);req(Number.isInteger(r.event_count)&&r.event_count>0,'delivery.event_count invalid');req(Number.isInteger(r.display_update_count)&&r.display_update_count>0,'delivery.display_update_count invalid');
 str(r.accepted_chain_id,'delivery.accepted_chain_id',ID);str(r.accepted_run_id,'delivery.accepted_run_id',ID);nni(r.accepted_run_epoch,'delivery.accepted_run_epoch');str(r.accepted_intent_ref,'delivery.accepted_intent_ref');nni(r.accepted_head_sequence,'delivery.accepted_head_sequence');str(r.accepted_projection_fingerprint,'delivery.accepted_projection_fingerprint',FP);
 req(Array.isArray(r.dispositions)&&r.dispositions.length===r.event_count,'delivery.dispositions must match event_count');
 r.dispositions.forEach((d,i)=>{exact(d,X,`delivery.dispositions[${i}]`);req(d.delivery_sequence===i,`delivery.dispositions[${i}].delivery_sequence mismatch`);req(d.new_progress_created_by_delivery===false&&d.authority_established===false&&d.execution_admitted===false,`delivery.dispositions[${i}] non-effects violated`);});
 const last=r.dispositions.at(-1);req(last.accepted_head_sequence_after===r.accepted_head_sequence&&last.accepted_projection_fingerprint_after===r.accepted_projection_fingerprint,'delivery final disposition mismatch');
 ['delivery_creates_progress','duplicate_delivery_counts_as_progress','reconnect_restores_authority','stale_projection_can_replace_display','transport_events_prove_liveness','execution_admitted','authority_established','private_reasoning_included'].forEach(k=>req(r[k]===false,`delivery.${k} must remain false`));
 time(r.assessed_at,'delivery.assessed_at');str(r.fingerprint_sha256,'delivery.fingerprint_sha256',FP);req(r.fingerprint_sha256===canonicalFingerprint(r),'delivery.fingerprint_sha256 mismatch');return true;
}
function validateContinuation(r){
 exact(r,C,'continuation_receipt');req(r.protocol==='FCL'&&r.version==='0.1'&&r.receipt_type==='ContinuationReceipt','continuation header mismatch');str(r.predecessor_run_id,'continuation.predecessor_run_id',ID);nni(r.predecessor_run_epoch,'continuation.predecessor_run_epoch');req(r.predecessor_terminal_state==='TIMED_OUT_CLOSED','continuation predecessor must be TIMED_OUT_CLOSED');str(r.terminal_receipt_fingerprint,'continuation.terminal_receipt_fingerprint',FP);
 req(r.predecessor_resurrection_admitted===false,'continuation predecessor resurrection must remain false');req(r.predecessor_authority_reacquired===false,'continuation predecessor authority reacquisition must remain false');str(r.successor_run_id,'continuation.successor_run_id',ID);nni(r.successor_run_epoch,'continuation.successor_run_epoch');req(r.successor_run_id!==r.predecessor_run_id,'continuation successor_run_id must differ');req(r.successor_run_epoch>r.predecessor_run_epoch,'continuation successor epoch must advance');
 req(r.successor_requires_fresh_authority===true,'continuation successor requires fresh authority');req(r.transferable_hidden_reasoning===false,'continuation transferable_hidden_reasoning must remain false');str(r.intent_ref,'continuation.intent_ref');if(r.last_checkpoint_ref!==null)str(r.last_checkpoint_ref,'continuation.last_checkpoint_ref');arr(r.completed_refs,'continuation.completed_refs');arr(r.unresolved_work,'continuation.unresolved_work',1);arr(r.constraints,'continuation.constraints');arr(r.non_effects,'continuation.non_effects');req(r.status==='SUCCESSOR_ADMISSIBLE','continuation status invalid');time(r.created_at,'continuation.created_at');str(r.fingerprint_sha256,'continuation.fingerprint_sha256',FP);req(r.fingerprint_sha256===canonicalFingerprint(r),'continuation.fingerprint_sha256 mismatch');return true;
}
function validateHandoff(h){
 exact(h,H,'handoff');req(h.protocol==='FCL'&&h.version==='0.1'&&h.profile==='successor-ui-handoff-v0.1','handoff header mismatch');str(h.handoff_id,'handoff.handoff_id',ID);exact(h.origin,['repository','revision','tree'],'handoff.origin');req(h.origin.repository==='Matawaka/uu-aap','handoff.origin.repository mismatch');str(h.origin.revision,'handoff.origin.revision',SHA);str(h.origin.tree,'handoff.origin.tree',SHA);
 try{validateProjection(h.predecessor_terminal_projection,'predecessor_terminal_projection');validateProjection(h.successor_projection,'successor_projection');}catch(e){throw new FCLHandoffError(e.message);}
 validateDelivery(h.predecessor_delivery_assessment);validateContinuation(h.continuation_receipt);
 const d=h.predecessor_delivery_assessment,p=h.predecessor_terminal_projection,c=h.continuation_receipt,s=h.successor_projection;
 req(d.terminal===true&&d.continuation_available===true&&d.human_status==='CONTINUATION_AVAILABLE'&&d.next_safe_action==='CREATE_SUCCESSOR_RUN','predecessor delivery assessment must be terminal and continuation-ready');
 req(p.terminal===true,'predecessor terminal projection must be terminal');req(p.fingerprint_sha256===d.accepted_projection_fingerprint,'predecessor terminal projection must equal delivered terminal display');req(p.chain_id===d.accepted_chain_id&&p.run_id===d.accepted_run_id&&p.run_epoch===d.accepted_run_epoch&&p.intent_ref===d.accepted_intent_ref&&p.head_sequence===d.accepted_head_sequence,'predecessor delivered identity mismatch');
 req(c.terminal_receipt_fingerprint===p.head_fingerprint,'continuation terminal receipt fingerprint must bind predecessor projection head');req(c.predecessor_run_id===p.run_id&&c.predecessor_run_epoch===p.run_epoch,'continuation predecessor identity mismatch');req(c.intent_ref===p.intent_ref,'continuation intent drift');req(c.last_checkpoint_ref===p.checkpoint_ref,'continuation checkpoint mismatch');
 req(s.run_id===c.successor_run_id&&s.run_epoch===c.successor_run_epoch,'successor projection identity mismatch');req(s.intent_ref===c.intent_ref,'successor projection intent drift');req(s.run_id!==p.run_id,'successor cannot reuse predecessor run_id');req(s.run_epoch>p.run_epoch,'successor epoch must advance');req(s.chain_id!==p.chain_id,'successor chain must be distinct');req(s.terminal===false,'first successor projection must be non-terminal');req(s.head_sequence===0&&s.chain_length===1,'first slice requires successor projection sequence 0 / chain_length 1');req(s.checkpoint_ref===c.last_checkpoint_ref,'successor checkpoint mismatch');
 str(h.successor_display_predecessor_projection_fingerprint,'handoff.successor_display_predecessor_projection_fingerprint',FP);req(h.successor_display_predecessor_projection_fingerprint===p.fingerprint_sha256,'handoff display predecessor binding mismatch');
 const ht=time(h.handoff_at,'handoff.handoff_at');req(time(p.projected_at,'predecessor.projected_at')<=time(d.assessed_at,'delivery.assessed_at'),'predecessor delivery assessment cannot precede terminal projection');req(time(d.assessed_at,'delivery.assessed_at')<=ht&&time(c.created_at,'continuation.created_at')<=ht&&time(s.projected_at,'successor.projected_at')<=ht,'handoff cannot precede required evidence');req(time(c.created_at,'continuation.created_at')<=time(s.projected_at,'successor.projected_at'),'successor projection cannot precede continuation receipt');return true;
}
function buildHandoffReceipt(h){
 validateHandoff(h);const d=h.predecessor_delivery_assessment,p=h.predecessor_terminal_projection,c=h.continuation_receipt,s=h.successor_projection;
 const r={protocol:'FCL',version:'0.1',receipt_type:'SuccessorUIHandoffReceipt',handoff_id:h.handoff_id,predecessor_session_id:d.session_id,predecessor_chain_id:p.chain_id,predecessor_run_id:p.run_id,predecessor_run_epoch:p.run_epoch,predecessor_terminal_projection_fingerprint:p.fingerprint_sha256,predecessor_terminal_receipt_fingerprint:p.head_fingerprint,predecessor_terminal_preserved:true,continuation_receipt_fingerprint:c.fingerprint_sha256,successor_chain_id:s.chain_id,successor_run_id:s.run_id,successor_run_epoch:s.run_epoch,successor_projection_fingerprint:s.fingerprint_sha256,display_predecessor_projection_fingerprint:h.successor_display_predecessor_projection_fingerprint,intent_ref:s.intent_ref,checkpoint_ref:s.checkpoint_ref,human_status:'CONTINUED_ON_SUCCESSOR',predecessor_terminal_visible:true,successor_primary_display:true,predecessor_resurrection_admitted:false,predecessor_authority_reacquired:false,run_identity_reused:false,intent_continuity_preserved:true,checkpoint_continuity_preserved:true,hidden_reasoning_transferred:false,authority_transferred_by_handoff:false,successor_requires_fresh_authority:true,execution_admitted:false,authority_established:false,next_safe_action:'WAIT_FOR_SUCCESSOR_PROGRESS',handoff_at:h.handoff_at,fingerprint_sha256:''};r.fingerprint_sha256=canonicalFingerprint(r);return r;
}
const read=p=>JSON.parse(p==='-'?fs.readFileSync(0,'utf8'):fs.readFileSync(path.resolve(p),'utf8'));
const print=v=>process.stdout.write(`${JSON.stringify(v,null,2)}\n`);
function main(a){const [cmd,p,...x]=a;if(!cmd||['help','--help','-h'].includes(cmd)){req(!p&&!x.length,'help accepts no extra arguments');process.stdout.write('FCL Successor UI Handoff v0.1 read-only CLI\nUsage: handoff.js validate|assess <handoff.json|->\nNo resume/execute/send/switch/activate command exists.\n');return;}req(!x.length,'unexpected extra arguments');req(['validate','assess'].includes(cmd),`unsupported command: ${cmd}`);req(p,`${cmd} requires an input path`);const h=read(p);if(cmd==='validate'){validateHandoff(h);print({protocol:'FCL',version:'0.1',status:'VALID',handoff_id:h.handoff_id,execution_admitted:false,authority_established:false});}else print(buildHandoffReceipt(h));}
if(require.main===module){try{main(process.argv.slice(2));}catch(e){if(e instanceof FCLHandoffError){process.stderr.write(`FCL Handoff validation error: ${e.message}\n`);process.exitCode=1;}else throw e;}}
module.exports={FCLHandoffError,buildHandoffReceipt,canonicalFingerprint,validateContinuation,validateDelivery,validateHandoff};
