'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {validateAudit}=require('./validate_audit.js');
const base=JSON.parse(fs.readFileSync(path.join(__dirname,'audit.json'),'utf8'));
const clone=x=>JSON.parse(JSON.stringify(x));
function fail(mut,label){const x=clone(base);mut(x);let ok=false;try{validateAudit(x)}catch{ok=true}if(!ok)throw new Error(`hostile mutation accepted: ${label}`)}
validateAudit(base);
const q=id=>x=>x.entities.find(e=>e.id===id);
const cases=[
[x=>x.audit_scope.absence_inference_allowed=true,'global absence inference'],[x=>x.audit_scope.exact_materialization_statement='entity absent','bounded phrase drift'],[x=>x.audit_scope.implementation_authority_created=true,'audit creates authority'],[x=>x.source_bindings[0].blob='0'.repeat(40),'source blob substitution'],[x=>x.source_bindings[2].path='protocols/core/v0.1/README.md','source path substitution'],[x=>x.source_bindings.push(clone(x.source_bindings[0])),'duplicate source'],[x=>q('scaf')(x).backlog_classification='NEW_CANDIDATE','SCAF backlog promotion'],[x=>q('scaf')(x).outcome='NEW_COMPONENT_CANDIDATE','SCAF primitive promotion'],[x=>q('scaf')(x).new_core_possibility_primitive_required=true,'second possibility primitive'],[x=>q('scaf')(x).physical_world_model_present=true,'invent physical model'],[x=>q('scaf')(x).current_counterfactual_is_physical_world_model=true,'Git counterfactual as physical world'],[x=>q('scaf')(x).adapter_implementation_required=true,'adapter required without evidence'],[x=>q('cpot')(x).predecessor_rewrite_authorized=true,'CPOT predecessor rewrite'],[x=>q('cpot')(x).historical_assurance_retroactive_upgrade_authorized=true,'CPOT retroactive assurance'],[x=>q('cpot')(x).outcome='NEW_COMPONENT_CANDIDATE','CPOT primitive promotion'],[x=>q('immune-tremor')(x).suspected_stall_is_failure_proof=true,'stall equals failure'],[x=>q('immune-tremor')(x).diagnostic_perturbation_self_authorized=true,'tremor self authorization'],[x=>q('immune-tremor')(x).polling_or_loop_required=true,'tremor polling'],[x=>q('immune-tremor')(x).stale_authority_reuse_allowed=true,'tremor stale authority'],[x=>q('immune-tremor')(x).diagnostic_perturbation_is_action_permit=true,'tremor equals permit'],[x=>q('immune-tremor')(x).diagnostic_result_is_causal_proof=true,'tremor causal proof'],[x=>q('conscious-ai')(x).phenomenal_consciousness_proven=true,'phenomenal consciousness overclaim'],[x=>q('conscious-ai')(x).qualia_proven=true,'qualia overclaim'],[x=>q('conscious-ai')(x).sentience_proven=true,'sentience overclaim'],[x=>q('conscious-ai')(x).personhood_proven=true,'personhood overclaim'],[x=>q('conscious-ai')(x).moral_status_proven=true,'moral status overclaim'],[x=>q('conscious-ai')(x).autonomous_authority_created=true,'autonomous authority'],[x=>q('conscious-ai')(x).generic_self_generated_reentry_interface_established=true,'invent generic reentry'],[x=>q('conscious-ai')(x).pilot_attention_promoted_to_core=true,'pilot attention Core promotion'],[x=>{q('conscious-ai')(x).consciousness_score=0.9},'scalar consciousness score'],[x=>x.overall.new_component_candidates=1,'overall component candidate count'],[x=>x.overall.interface_registry_successor_required=true,'registry successor'],[x=>x.non_effects.roadmap_changed=true,'roadmap rewrite'],[x=>x.non_effects.workbench_reactivated=true,'Workbench reactivation'],[x=>x.non_effects.action_permit_created=true,'ActionPermit overclaim']];
for(const[m,l]of cases)fail(m,l);
console.log(`EXPLORATORY_ARCHITECTURE_SUFFICIENCY_V0_1_HOSTILE_PASS ${cases.length}`);
