'use strict';
const fs=require('node:fs'); const path=require('node:path'); const assert=require('node:assert/strict');
const Candidate=require('./compose.js');
const RERC=require('../../../integration/rerc/v0.1/rerc.js');
const manifest=require('./candidate-manifest.json'); Candidate.validateManifest(manifest);
const out=process.argv[2]||'/tmp/recoverable-state-infrastructure-v0.1'; fs.mkdirSync(out,{recursive:true});
const capability={artifact_type:'EventResponsiveDormantCapability',version:'0.1',capability_id:'cap:rsic',context_ref:'ctx:rsic',scope_ref:'scope:rsic',wake_signal_kinds:['NEW_EVIDENCE'],state:'DORMANT',checkpoint_refs:['checkpoint:rsic'],provenance_refs:['evidence:rsic'],predecessor:{run_id:'run:old',epoch:3,lease_ref:'lease:expired',intent_ref:'intent:old',action_permit_ref:'permit:consumed'},polling_enabled:false,background_activity_authorized:false,active_process:false,authority_inherited:false,intent_inherited:false,action_permit_inherited:false,external_effect_authority:false};
const signal={artifact_type:'EventResponsiveWakeSignal',version:'0.1',signal_id:'signal:rsic',kind:'NEW_EVIDENCE',context_ref:'ctx:rsic',scope_ref:'scope:rsic',evidence_ref:'event:new',source_assurance:'EVIDENCE_BOUND'};
const graph={artifact_type:'RERCRelationGraph',version:'0.1',graph_kind:'OBSERVED',graph_id:'graph:rsic',nodes:[{node_id:'a',kind:'claim',evidence_refs:['ev:a']},{node_id:'b',kind:'claim',evidence_refs:['ev:b']}],edges:[{edge_id:'r1',from:'a',to:'b',relation_type:'supports',redundancy_class:'REPRESENTATIONAL',redundancy_group:'g1',evidence_refs:['ev:r1'],ontological_status:'OBSERVED_RELATION'},{edge_id:'r2',from:'a',to:'b',relation_type:'supports',redundancy_class:'REPRESENTATIONAL',redundancy_group:'g1',evidence_refs:['ev:r2'],ontological_status:'OBSERVED_RELATION'},{edge_id:'p1',from:'b',to:'a',relation_type:'safety_crosscheck',redundancy_class:'PROTECTIVE',redundancy_group:'protect',evidence_refs:['ev:p1'],ontological_status:'OBSERVED_RELATION'}],source_graph_digest:null,claims:{authority_created:false,facts_created:false,evidence_deleted:false,relations_invalidated:false}};
const input={work_context_ref:'work:rsic:1',dormancy_input:{dormant_capability:capability,wake_signal:signal,checks:{current_evidence:true,current_authority:true,intent_corridor:true}},rerc_input:{observed_graph:graph,suppress_edge_ids:['r2'],request_id:'compose:1'}};
const result=Candidate.runCandidate(input);
assert.equal(result.composition_receipt.composition_state,'COMPOSED_READY_FOR_SEPARATE_ACTION_ADMISSION');
assert.deepEqual(result.composition_receipt.possible_next_interfaces,['PreActionEvidenceBundle']);
assert.equal(result.composition_receipt.automatic_transition,false);
assert.deepEqual(result.restored_graph,graph);
assert.equal(RERC.digest(result.restored_graph),result.suppression_receipt.source_graph_digest);
assert.ok(Object.values(result.composition_receipt.claims).every(v=>v===false));
for(const [n,v] of Object.entries({'wake-receipt.json':result.wake_receipt,'operational-graph.json':result.operational_graph,'suppression-receipt.json':result.suppression_receipt,'restored-graph.json':result.restored_graph,'composition-receipt.json':result.composition_receipt})) fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n');
const stale=Candidate.runCandidate({...input,dormancy_input:{...input.dormancy_input,checks:{current_evidence:true,current_authority:false,intent_corridor:true}},rerc_input:{...input.rerc_input,request_id:'compose:2'}});
assert.equal(stale.composition_receipt.composition_state,'COMPOSED_NO_ACTION_ADMISSION'); assert.deepEqual(stale.composition_receipt.possible_next_interfaces,[]);
function reject(n,fn,pat){let e=null;try{fn();}catch(x){e=x;}assert.ok(e,`${n}: expected reject`);if(pat)assert.match(e.message,pat);}
const badWake=structuredClone(result.wake_receipt);badWake.claims.authority_created=true;
reject('ERD authority escalation',()=>Candidate.composeOutputs({work_context_ref:'work:x',wake_receipt:badWake,operational_graph:result.operational_graph,suppression_receipt:result.suppression_receipt}),/authority\/non-effect/);
const badSupp=structuredClone(result.suppression_receipt);badSupp.exact_restore_verified=false;
reject('RERC nonreversible',()=>Candidate.composeOutputs({work_context_ref:'work:x',wake_receipt:result.wake_receipt,operational_graph:result.operational_graph,suppression_receipt:badSupp}),/exact restore/);
const badOp=structuredClone(result.operational_graph);badOp.edges[0].evidence_refs=['tampered'];
reject('RERC operational mutation',()=>Candidate.composeOutputs({work_context_ref:'work:x',wake_receipt:result.wake_receipt,operational_graph:badOp,suppression_receipt:result.suppression_receipt}),/operational graph digest/);
const badManifest=structuredClone(manifest);badManifest.components[1].module_blob='0'.repeat(40);
reject('manifest component substitution',()=>Candidate.validateManifest(badManifest),/candidate component substitution/);
const sub=structuredClone(result.composition_receipt);sub.component_bindings.rerc.module_blob='0'.repeat(40);
reject('component substitution',()=>Candidate.validateCompositionReceipt(sub),/RERC component substitution/);
const auto=structuredClone(result.composition_receipt);auto.automatic_transition=true;
reject('automatic transition',()=>Candidate.validateCompositionReceipt(auto),/automatic transition/);
const perf=structuredClone(result.composition_receipt);perf.claims.performance_gain_proven=true;
reject('performance overclaim',()=>Candidate.validateCompositionReceipt(perf),/unsafe composition claim/);
const shared=structuredClone(result.composition_receipt);shared.claims.shared_world_identity_proven=true;
reject('shared identity overclaim',()=>Candidate.validateCompositionReceipt(shared),/unsafe composition claim/);
const noReady=structuredClone(stale.composition_receipt);noReady.possible_next_interfaces=['PreActionEvidenceBundle'];
reject('next interface without ERD ready',()=>Candidate.validateCompositionReceipt(noReady),/non-ready composition state/);
console.log('RECOVERABLE_STATE_INFRASTRUCTURE_CANDIDATE_V0_1_PASS');
